name: Sync Gist to Repo

on:
  schedule:
    - cron: '*/30 * * * *'  # æ¯ 30 åˆ†é’Ÿè¿è¡Œä¸€æ¬¡
  workflow_dispatch:        # æ”¯æŒæ‰‹åŠ¨è§¦å‘

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Gist all.yaml
        run: |
          curl -sSL https://gist.githubusercontent.com/godfather216/3e98be75088df4bd543d83325f788297/raw/8785ab6f96d945a78905ed5adab998069f66e8b2/2.yaml -o all.yaml

      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/${{ github.repository }}
          git add all.yaml
          git commit -m "ğŸ”„ è‡ªåŠ¨åŒæ­¥ Gist all.yaml - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
