name: Sync Gist to Repo

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout using GH_PAT and Sync Gists
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://x-access-token:$GH_PAT@github.com/${{ github.repository }} repo
          cd repo

          # ä¸‹è½½å¤šä¸ª Gist æ–‡ä»¶ï¼Œç›´æ¥å‘½åä¸ºç›®æ ‡æ–‡ä»¶å
          curl -sSL https://gist.githubusercontent.com/godfather216/3e98be75088df4bd543d83325f788297/raw/1.yaml -o all.yaml
          curl -sSL https://gist.githubusercontent.com/godfather216/3e98be75088df4bd543d83325f788297/raw/2.yaml -o cn.yaml

          git config user.name github-actions
          git config user.email actions@github.com

          git add all.yaml cn.yaml
          git commit -m "ğŸ”„ è‡ªåŠ¨åŒæ­¥å¤šä¸ª Gist æ–‡ä»¶ - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
